package utils

var STATUS = map[string]string{
	"0": "PENDIENTE",
	"1": "APROBADA",
	"2": "CANCELADA",
	"4": "RECHAZADA",
	"5": "EXPIRADA",
}

var STATUS_DETALS = map[string]string{
	"0":  "Esperando para ser Pagada.",
	"1":  "Se requiere verificación, por favor revise la sección de Verificar",
	"2":  "Pagada Parcialmente",
	"3":  "Pagada",
	"4":  "En Disputa",
	"5":  "Sobrepagada",
	"6":  "Fraude",
	"7":  "Reverso",
	"8":  "Contracargo",
	"9":  "Rechazada por el procesador",
	"10": "Error en el sistema",
	"11": "Fraude detectado por Nuvei",
	"12": "Blacklist de Nuvei",
	"13": "Tiempo de tolerancia",
	"14": "Expirada por Nuvei",
	"15": "Expirado por el carrier",
	"16": "Rechazado por Nuvei",
	"17": "Abandonada por Nuvei",
	"18": "Abandonada por el cliente",
	"19": "Código de autorización invalido",
	"20": "Código de autorización expirado",
	"21": "Fraude Nuvei - Reverso pendiente",
	"22": "AuthCode Inválido - Reverso pendiente",
	"23": "AuthCode Expirado - Reverso pendiente",
	"24": "Fraude Nuvei - Reverso solicitado",
	"25": "AuthCode Inválido - Reverso solicitado",
	"26": "AuthCode Expirado - Reverso solicitado",
	"27": "Comercio - Reverso pendiente",
	"28": "Comercio - Reverso solicitado",
	"29": "Anulada",
	"30": "Transacción asentada (solo para Ecuador)",
	"31": "Esperando OTP",
	"32": "OTP validado correctamente",
	"33": "OTP no validado",
	"34": "Reverso parcial",
	"35": "Método 3DS solicitado, esperando para continuar",
	"36": "Desafío 3DS solicitado, esperando el CRES",
	"37": "Rechazada por 3DS",
	"47": "Validación de CPF fallida",
	"48": "Autenticado por 3DS",
}
